<a href="javascript:grin('[smile1]')" ><img src="<?php echo TEMPLATE_URL; ?>images/face/1.gif"/></a>
<a href="javascript:grin('[smile2]')" ><img src="<?php echo TEMPLATE_URL; ?>images/face/2.gif"/></a>
<a href="javascript:grin('[smile3]')" ><img src="<?php echo TEMPLATE_URL; ?>images/face/3.gif"/></a>
<a href="javascript:grin('[smile4]')" ><img src="<?php echo TEMPLATE_URL; ?>images/face/4.gif"/></a>
<a href="javascript:grin('[smile5]')" ><img src="<?php echo TEMPLATE_URL; ?>images/face/5.gif"/></a>
<a href="javascript:grin('[smile6]')" ><img src="<?php echo TEMPLATE_URL; ?>images/face/6.gif"/></a>
<a href="javascript:grin('[smile7]')" ><img src="<?php echo TEMPLATE_URL; ?>images/face/7.gif"/></a>
<a href="javascript:grin('[smile8]')" ><img src="<?php echo TEMPLATE_URL; ?>images/face/8.gif"/></a>
<a href="javascript:grin('[smile9]')" ><img src="<?php echo TEMPLATE_URL; ?>images/face/9.gif"/></a>
<a href="javascript:grin('[smile10]')" ><img src="<?php echo TEMPLATE_URL; ?>images/face/10.gif"/></a>
<a href="javascript:grin('[smile11]')" ><img src="<?php echo TEMPLATE_URL; ?>images/face/11.gif"/></a>
<a href="javascript:grin('[smile12]')" ><img src="<?php echo TEMPLATE_URL; ?>images/face/12.gif"/></a>
<a href="javascript:grin('[smile13]')" ><img src="<?php echo TEMPLATE_URL; ?>images/face/13.gif"/></a>
<a href="javascript:grin('[smile14]')" ><img src="<?php echo TEMPLATE_URL; ?>images/face/14.gif"/></a>
<a href="javascript:grin('[smile15]')" ><img src="<?php echo TEMPLATE_URL; ?>images/face/15.gif"/></a>
<a href="javascript:grin('[smile16]')" ><img src="<?php echo TEMPLATE_URL; ?>images/face/16.gif"/></a>
<a href="javascript:grin('[smile17]')" ><img src="<?php echo TEMPLATE_URL; ?>images/face/17.gif"/></a>
<a href="javascript:grin('[smile18]')" ><img src="<?php echo TEMPLATE_URL; ?>images/face/18.gif"/></a>
<a href="javascript:grin('[smile19]')" ><img src="<?php echo TEMPLATE_URL; ?>images/face/19.gif"/></a>
<a href="javascript:grin('[smile20]')" ><img src="<?php echo TEMPLATE_URL; ?>images/face/20.gif"/></a>